name = "serial-number-app-v2"
client_id = "16749a153d22495690ab9a2e891da095"
application_url = "https://serial-number-app-v2.onrender.com"
embedded = true

[access_scopes]
scopes = "write_products,read_orders,write_orders,read_customers"

[auth]
redirect_urls = [
  "https://serial-number-app-v2.onrender.com/auth/callback",
  "https://serial-number-app-v2.onrender.com/auth/shopify/callback",
  "https://serial-number-app-v2.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2025-10"
